#!/bin/sh
set -e

# MIND Framework Installer
# https://github.com/mindwai/mind-framework
# Usage: ./install.sh [target_dir]  |  ./install.sh --update [target_dir]

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
UPDATE_ONLY=false

# Parse args
case "${1:-}" in
  --update) UPDATE_ONLY=true; TARGET="${2:-.}" ;;
  *)        TARGET="${1:-.}" ;;
esac

TARGET="$(cd "$TARGET" 2>/dev/null && pwd)" || { echo "Error: target directory '$1' does not exist."; exit 1; }
[ -d "$SCRIPT_DIR/.mind" ] || { echo "Error: source .mind/ not found in $SCRIPT_DIR"; exit 1; }

# --- Idempotency: detect existing install ---
if [ -d "$TARGET/.mind" ] && [ "$UPDATE_ONLY" = false ]; then
  printf "Existing .mind/ detected in %s.\n" "$TARGET"
  printf "  [u] Update with backup (default)\n"
  printf "  [f] Fresh install with backup\n"
  printf "  [c] Cancel\n"
  printf "Choice [u/f/c]: "
  read -r choice
  case "${choice:-u}" in
    f|F)
      echo "Backing up .mind/ to .mind.bak/ ..."
      rm -rf "$TARGET/.mind.bak"
      cp -r "$TARGET/.mind" "$TARGET/.mind.bak"
      rm -rf "$TARGET/.mind"
      ;;
    c|C)
      echo "Cancelled."; exit 0
      ;;
    *)
      echo "Backing up .mind/ to .mind.bak/ ..."
      rm -rf "$TARGET/.mind.bak"
      cp -r "$TARGET/.mind" "$TARGET/.mind.bak"
      ;;
  esac
fi

if [ "$UPDATE_ONLY" = true ] && [ -d "$TARGET/.mind" ]; then
  echo "Backing up before update ..."
  rm -rf "$TARGET/.mind.bak"
  cp -r "$TARGET/.mind" "$TARGET/.mind.bak"
fi

# --- Copy .mind/ (skip on --update) ---
if [ "$UPDATE_ONLY" = false ]; then
  echo "Copying .mind/ to $TARGET ..."
  cp -r "$SCRIPT_DIR/.mind" "$TARGET/.mind"
fi

# --- Create features directory ---
mkdir -p "$TARGET/.mind/features"

# --- Generate MIND.md ---
list_files() {
  dir="$1"; prefix="$2"
  for f in "$dir"/*.md; do
    [ -f "$f" ] || continue
    name="$(basename "$f" .md)"
    echo "- [${name}]($prefix/${name}.md)"
  done
}

echo "Generating MIND.md ..."
RULES_LIST="$(list_files "$TARGET/.mind/rules" ".mind/rules")"
TEMPLATES_LIST="$(list_files "$TARGET/.mind/templates" ".mind/templates")"

cat > "$TARGET/MIND.md" << MINDEOF
> This file is auto-generated by install.sh.
> To update after adding personas/commands/rules, run: ./install.sh --update

# MIND Framework

## Rules (read these first)

Before any task, read the applicable rules in this order:

1. [code-standards](.mind/rules/code-standards.md) -- naming, size limits, side effects, nesting
2. [tests](.mind/rules/tests.md) -- AAA/GWT structure, coverage, mocking, anti-patterns
3. [git-branching](.mind/rules/git-branching.md) -- branch strategy, naming, merge flow

Add project-specific rules to .mind/rules/ and run ./install.sh --update.

## Pipeline

See [.mind/config.yaml](.mind/config.yaml) for the full pipeline definition.

\`\`\`
create-prd -> clarify-prd -> create-techspec -> validate-spec ->
create-tasks -> execute-task -> execute-review -> execute-qa
\`\`\`

Each step is a command file in .mind/commands/. Steps marked optional
in config.yaml can be skipped without breaking the flow.

## Workflow State

Artifacts use YAML frontmatter to track status:

\`\`\`yaml
---
status: todo | working | done | failed
---
\`\`\`

Features live in \`.mind/features/{feature-id}/\` with:

\`\`\`
.mind/features/{feature-id}/
  prd.md
  techspec.md
  tasks/task-001.md, task-002.md, ...
  reviews/review-001.md
  qa/qa-001.md
\`\`\`

## Task Lifecycle

Every task follows a strict state machine:

1. **claim** -- agent claims the task, status becomes working
2. **implement** -- agent writes code, commits to task branch
3. **submit_qa** -- agent submits QA verdict (PASS/FAIL + findings)
4. **complete** -- task marked done after QA passes

Skipping states leads to state corruption. Always follow the full sequence.

## Personas

- **senior-developer** -- Implementation: code quality, resilience, standards conformance
- **code-reviewer** -- Code review: anti-rationalization, dynamic rule reading
- **qa-engineer** -- Adversarial QA: structured verdicts, requirement validation
- **tech-writer** -- Documentation: consolidation, zero invention
- **product-owner** -- Requirements: never assumes, always clarifies

See .mind/personas/ for full persona definitions.

## Commands

- **create-prd** -- Specify product requirements from a feature request
- **clarify-prd** -- Resolve ambiguities in an existing PRD
- **create-techspec** -- Design the technical solution for a PRD
- **validate-spec** -- Cross-validate PRD against TechSpec
- **create-tasks** -- Decompose a feature into incremental tasks
- **execute-task** -- Implement a single task with full lifecycle
- **execute-review** -- Review code changes against project rules
- **execute-qa** -- Validate implementation against requirements

See .mind/commands/ for full command definitions.

## Quality Gates

Pause for human approval at these points:

- After create-prd (before techspec)
- After create-techspec (before tasks)
- After execute-review (before merge)
- After execute-qa (before closing feature)

Never skip a gate. If in doubt, pause and ask.

## Templates

Output formats in .mind/templates/:

$TEMPLATES_LIST

## Beyond Local

For teams needing enforcement, memory, and multi-agent orchestration:
https://mindwai.com
MINDEOF

# --- Create shim files ---
for shim in AGENTS.md CLAUDE.md .cursorrules; do
  cat > "$TARGET/$shim" << EOF
# $shim
# This project uses the MIND Framework. Read MIND.md for the full index.
Read MIND.md first, then follow the rules and commands defined there.
EOF
done

echo ""
echo "MIND Framework installed successfully!"
echo ""
echo "Next steps:"
echo "  1. Read MIND.md — it's the index your AI agent reads first"
echo "  2. Tell your AI agent: \"Read MIND.md and follow the framework\""
echo "  3. Start your first feature: \"Create a PRD for [your feature]\""
