#!/bin/sh
set -e

# MIND Framework Installer v0.2.0
# https://github.com/mindwai/mind-framework
# Usage: ./install.sh [target_dir]  |  ./install.sh --update [target_dir]

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
UPDATE_ONLY=false

# Parse args
case "${1:-}" in
  --update) UPDATE_ONLY=true; TARGET="${2:-.}" ;;
  *)        TARGET="${1:-.}" ;;
esac

TARGET="$(cd "$TARGET" 2>/dev/null && pwd)" || { echo "Error: target directory '$1' does not exist."; exit 1; }
[ -d "$SCRIPT_DIR/.mind" ] || { echo "Error: source .mind/ not found in $SCRIPT_DIR"; exit 1; }

# --- Idempotency: detect existing install ---
if [ -d "$TARGET/.mind" ] && [ "$UPDATE_ONLY" = false ]; then
  printf "Existing .mind/ detected in %s.\n" "$TARGET"
  printf "  [u] Update with backup (default)\n"
  printf "  [f] Fresh install with backup\n"
  printf "  [c] Cancel\n"
  printf "Choice [u/f/c]: "
  read -r choice
  case "${choice:-u}" in
    f|F)
      echo "Backing up .mind/ to .mind.bak/ ..."
      rm -rf "$TARGET/.mind.bak"
      cp -r "$TARGET/.mind" "$TARGET/.mind.bak"
      rm -rf "$TARGET/.mind"
      ;;
    c|C)
      echo "Cancelled."; exit 0
      ;;
    *)
      echo "Backing up .mind/ to .mind.bak/ ..."
      rm -rf "$TARGET/.mind.bak"
      cp -r "$TARGET/.mind" "$TARGET/.mind.bak"
      ;;
  esac
fi

if [ "$UPDATE_ONLY" = true ] && [ -d "$TARGET/.mind" ]; then
  echo "Backing up before update ..."
  rm -rf "$TARGET/.mind.bak"
  cp -r "$TARGET/.mind" "$TARGET/.mind.bak"
fi

# --- Copy .mind/ (skip on --update) ---
if [ "$UPDATE_ONLY" = false ]; then
  echo "Copying .mind/ to $TARGET ..."
  cp -r "$SCRIPT_DIR/.mind" "$TARGET/.mind"
fi

# --- Create directories ---
mkdir -p "$TARGET/.mind/features"
mkdir -p "$TARGET/.mind/skills"
mkdir -p "$TARGET/.mind/hooks/git"
mkdir -p "$TARGET/.mind/hooks/agent"

# --- Preserve custom content on update ---
if [ "$UPDATE_ONLY" = true ] && [ -d "$TARGET/.mind.bak" ]; then
  # Restore dev-created files that framework update may have missed
  for dir in skills hooks/git hooks/agent rules; do
    if [ -d "$TARGET/.mind.bak/$dir" ]; then
      cp -rn "$TARGET/.mind.bak/$dir/." "$TARGET/.mind/$dir/" 2>/dev/null || true
    fi
  done
fi

# --- Create .gitignore if not exists ---
if [ ! -f "$TARGET/.gitignore" ]; then
  cat > "$TARGET/.gitignore" << 'EOF'
# MIND Framework — personal overrides
.mind/config.local.yaml
EOF
elif ! grep -q "config.local.yaml" "$TARGET/.gitignore" 2>/dev/null; then
  echo ".mind/config.local.yaml" >> "$TARGET/.gitignore"
fi

# --- Copy config.local.yaml.example ---
if [ -f "$SCRIPT_DIR/.mind/config.local.yaml.example" ]; then
  cp -n "$SCRIPT_DIR/.mind/config.local.yaml.example" "$TARGET/.mind/config.local.yaml.example" 2>/dev/null || true
fi

# --- Copy install-git-hooks.sh ---
if [ -f "$SCRIPT_DIR/.mind/install-git-hooks.sh" ]; then
  cp "$SCRIPT_DIR/.mind/install-git-hooks.sh" "$TARGET/.mind/install-git-hooks.sh"
  chmod +x "$TARGET/.mind/install-git-hooks.sh"
fi

# --- Generate MIND.md ---
list_files() {
  dir="$1"; prefix="$2"
  for f in "$dir"/*.md; do
    [ -f "$f" ] || continue
    name="$(basename "$f" .md)"
    echo "- [${name}]($prefix/${name}.md)"
  done
}

echo "Generating MIND.md ..."
RULES_LIST="$(list_files "$TARGET/.mind/rules" ".mind/rules")"
TEMPLATES_LIST="$(list_files "$TARGET/.mind/templates" ".mind/templates")"

# Build skills list dynamically
SKILLS_LIST=""
for d in "$TARGET/.mind/skills"/*/; do
  [ -f "$d/SKILL.md" ] || continue
  name="$(basename "$d")"
  SKILLS_LIST="${SKILLS_LIST}- **${name}** -- See .mind/skills/${name}/SKILL.md
"
done

cat > "$TARGET/MIND.md" << MINDEOF
> This file is auto-generated by install.sh.
> To update after adding personas/commands/rules/skills, run: ./install.sh --update

# MIND Framework

## Rules (read these first)

Before any task, read the applicable rules:

$RULES_LIST

Rules with \`scope:\` in frontmatter apply only to matching file paths.
Rules without scope apply globally. Before modifying a file, check if
any rule has a matching scope.

If .mind/config.local.yaml exists, its values override config.yaml.

## Pipeline

See [.mind/config.yaml](.mind/config.yaml) for the full pipeline definition.

\`\`\`
create-prd -> clarify-prd -> create-techspec -> validate-spec ->
create-tasks -> execute-task -> execute-review -> execute-qa
\`\`\`

Each step is a command file in .mind/commands/. Steps marked optional
in config.yaml can be skipped without breaking the flow.

## Workflow State

Artifacts use YAML frontmatter to track status:

\`\`\`yaml
---
status: todo | working | done | failed
---
\`\`\`

Features live in \`.mind/features/{feature-id}/\` with:

\`\`\`
.mind/features/{feature-id}/
  prd.md
  techspec.md
  tasks/task-001.md, task-002.md, ...
  reviews/review-001.md
  qa/qa-001.md
\`\`\`

## Task Lifecycle

Every task follows a strict state machine:

1. **claim** -- agent claims the task, status becomes working
2. **implement** -- agent writes code, commits to task branch
3. **submit_qa** -- agent submits QA verdict (PASS/FAIL + findings)
4. **complete** -- task marked done after QA passes

Skipping states leads to state corruption. Always follow the full sequence.

## Skills

Before starting a task, scan .mind/skills/*/SKILL.md. If the task
description contains any trigger keyword OR the task modifies files
matching any trigger path, load that skill's full directory as context.

${SKILLS_LIST}See .mind/skills/README.md for details on triggers and structure.

## Personas

- **senior-developer** -- Implementation: code quality, resilience, standards conformance
- **code-reviewer** -- Code review: anti-rationalization, dynamic rule reading
- **qa-engineer** -- Adversarial QA: structured verdicts, requirement validation
- **tech-writer** -- Documentation: consolidation, zero invention
- **product-owner** -- Requirements: never assumes, always clarifies

See .mind/personas/ for full persona definitions.

## Commands

- **create-prd** -- Specify product requirements from a feature request
- **clarify-prd** -- Resolve ambiguities in an existing PRD
- **create-techspec** -- Design the technical solution for a PRD
- **validate-spec** -- Cross-validate PRD against TechSpec
- **create-tasks** -- Decompose a feature into incremental tasks
- **execute-task** -- Implement a single task with full lifecycle
- **execute-review** -- Review code changes against project rules
- **execute-qa** -- Validate implementation against requirements

See .mind/commands/ for full command definitions.

## Hooks

### Git hooks (enforcement)
Scripts in .mind/hooks/git/ are symlinked to .git/hooks/ and run
automatically on git events. Enable with: sh .mind/install-git-hooks.sh

### Agent hooks (convention, not enforcement)
Before running bash: sh .mind/hooks/agent/pre-bash.sh "\$COMMAND"
Before completing task: sh .mind/hooks/agent/pre-task-complete.sh
After writing a file: sh .mind/hooks/agent/post-file-write.sh "\$FILE"
If a hook exits non-zero, report the error and abort the action.

## Quality Gates

Pause for human approval at these points:

- After create-prd (before techspec)
- After create-techspec (before tasks)
- After execute-review (before merge)
- After execute-qa (before closing feature)

Never skip a gate. If in doubt, pause and ask.

## Templates

Output formats in .mind/templates/:

$TEMPLATES_LIST

## Beyond Local

For teams needing enforcement, memory, and multi-agent orchestration:
https://mindwai.com
MINDEOF

# --- Create shim files ---
cat > "$TARGET/AGENTS.md" << 'EOF'
# AGENTS.md
This project uses the MIND Framework.
See ./MIND.md for operating instructions.
EOF

cat > "$TARGET/CLAUDE.md" << 'EOF'
# CLAUDE.md
This project uses the MIND Framework.
See ./MIND.md for operating instructions.
EOF

cat > "$TARGET/.cursorrules" << 'EOF'
This project uses the MIND Framework.
See ./MIND.md for operating instructions.
Follow the pipeline defined in .mind/config.yaml.
EOF

# --- Git hook integration prompt ---
if [ -d "$TARGET/.git" ] && [ -d "$TARGET/.mind/hooks/git" ]; then
  printf "\nEnable git hook integration? [y/N]: "
  read -r ghook
  case "${ghook:-n}" in
    y|Y)
      sh "$TARGET/.mind/install-git-hooks.sh"
      ;;
    *)
      echo "  Skipped. Run .mind/install-git-hooks.sh later to enable."
      ;;
  esac
fi

echo ""
echo "MIND Framework installed successfully!"
echo ""
echo "Next steps:"
echo "  1. Read MIND.md — it's the index your AI agent reads first"
echo "  2. Tell your AI agent: \"Read MIND.md and follow the framework\""
echo "  3. Start your first feature: \"Create a PRD for [your feature]\""
